language: javascript
services: docker
env:
  global:
  - PROJECT_NAME=lpp-route-finder
  - PROJECT_VERSION=1.0.0
  - DOCKER_USERNAME=bezpov
  - secure: JwKtgnq0oiEIceOHiFcDweWk1Hfw/12ig1g7Q8ZvrlJOBMfTynrPdc/sbxqePlH7xlpiBl85L4l2eqvRLxxStlsQtW4YIsRuMMbjKhlBfFlmuOUbsgCoe+eVTNr4hXqyYNpT4OEkYTs9jeD/PnGGsHGt6CRPlSqDRNOnQiMG4twMkC33uekhsCYQZ2q6x3POWQi9KzaYa92AxmHVyzb2+ThhbwtXw2ZVSGLirDze2/mHUuvuzDizftxfDCz8QLsM2V/efjwlucDqbfNXrPbSRde9BrbifArIplMg1ueVvDyNalXC049UEQx1zDnXcwRA2umK635DpXyXVo2FZFJpaF6S/wBT3Cc+ROdsL3dA5wbClJtuqEPYeapJJjRelZju3RLg4wvIwqREkOoIrO3TssAEvZ7IdpPsYKvdwLI1wnWsrJrUQa4ZN/i77rnz78p2iVwlBw40poiM02wMWD6lDnyT0S0+E6OuKrvSJ9W+zPnuRmvtiELyOyKR837g7I8XXgidHcs/JsuOZ4N4F9Yk5LL+hdXYSr0i3bBOLKP6pczoh5r5lvEqffclXVfyLYeLl7zCtnsTsacxo36UQKBXxLGBQvDAoj6iq8Aydd/sHG1OAVDL5fHktmd0nD5GYFXls8OgfsXRYaYjqwj3pbc8OQBHQrbOjYtXhxGcAD00Dqo=
before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker image build -t $PROJECT_NAME:$PROJECT_VERSION .
- docker image tag $PROJECT_NAME:$PROJECT_VERSION $DOCKER_USERNAME/$PROJECT_NAME:$PROJECT_VERSION
- docker image push $DOCKER_USERNAME/$PROJECT_NAME
